{{- if .Values.global.oauthK8Config.withIngress -}}
{{- if .Values.global.oauthK8Config.withIngress.enabled -}}
{{- $fullName := include "oauth.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-int
  labels:
    {{- include "oauth.labels" . | nindent 4 }}
  annotations:
    {}
spec:
  {{- include "oauth.intIngress" . | nindent 2 }}
{{- end }}
{{- end }}