apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "oauth.fullname" . }}
  labels:
    {{- include "oauth.labels" . | nindent 4 }}
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  {{- toYaml .Values.global.oauthK8Config.efsPersistence.accessModes | nindent 4 }}
  persistentVolumeReclaimPolicy: {{ .Values.global.oauthK8Config.efsPersistence.reclaimPolicy | quote }}
  storageClassName: {{ .Values.global.oauthK8Config.efsPersistence.storageClassName | quote }}
  mountOptions:
  {{- toYaml .Values.global.oauthK8Config.efsPersistence.mountOptions | nindent 4 }}
  csi:
    driver: {{ .Values.global.oauthK8Config.efsPersistence.provisioner  | quote }}
    {{- if .Values.global.oauthK8Config.efsPersistence.accessPointId -}}
    volumeHandle: {{ printf "%s::%s" .Values.global.oauthK8Config.efsPersistence.fileSystemId .Values.global.oauthK8Config.efsPersistence.accessPointId }}
    {{- else -}}
    volumeHandle: {{ .Values.global.oauthK8Config.efsPersistence.fileSystemId }}
    {{- end -}}
  nfs:
    path: /tmp
    server: 172.17.0.2