# add security context to pvc
# pvc will have th mount - ~/.ec/.db

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "oauth.fullname" . }}
  labels:
    {{- include "oauth.labels" . | nindent 4 }}
spec:
  accessModes:
  {{- toYaml .Values.global.oauthK8Config.efsPersistence.accessModes | nindent 4 }}
  storageClassName: {{ .Values.global.oauthK8Config.efsPersistence.storageClassName | quote }}
  resources:
    requests:
      storage: 1Gi
