apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oauth.fullname" . }}
  labels:
    {{- include "oauth.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range (split "\n" .Values.global.oauthConfig) }}
  {{- $a := splitn "=" 2 . }}
  {{- if and (not (eq $a._1 "")) ($a._1) }}
  {{- if or (contains "CID" $a._0) (contains "CSC" $a._0) (contains "PVTKEY" $a._0) (contains "CA_PPRS" $a._0) }}
  {{ $a._0 }}: {{ $a._1|b64enc|quote }}
  {{- end }}
  {{- end }}
  {{- end -}}