{{- if .Values.global.ecServiceK8Config.withExtIngress -}}
{{- if .Values.global.ecServiceK8Config.withExtIngress.enabled -}}
{{- $fullName := include "ec-service.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1" }}
apiVersion: networking.k8s.io/v1
{{- else if $.Capabilities.APIVersions.Has "networking.k8s.io/v1beta1"}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-ext
  labels:
    {{- include "ec-service.labels" . | nindent 4 }}
  {{ if .Values.global.ecServiceK8Config.withExtIngress.ingressExtAnnotations }}
  {{- with .Values.global.ecServiceK8Config.withExtIngress.ingressExtAnnotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- else -}}
  annotations:
    {}
  {{- end }}
spec:
  {{- include "ec-service.extIngress" . | nindent 2 }}
{{- end }}
{{- end }}