{{- if .Values.global.ecServiceK8Config.withExtIngress -}}
{{- if .Values.global.ecServiceK8Config.withExtIngress.enabled -}}
{{- $fullName := include "ec-service.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-ext
  labels:
    {{- include "ec-service.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "nginx-ext"
spec:
  {{- include "ec-service.extIngress" . | nindent 2 }}
{{- end }}
{{- end }}