{{- if .Values.global.ecServiceK8Config.withIngress -}}
{{- if .Values.global.ecServiceK8Config.withIngress.enabled -}}
{{- $fullName := include "ec-service.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-int
  labels:
    {{- include "ec-service.labels" . | nindent 4 -}}
  {{ if .Values.global.ecServiceK8Config.withIngress.ingressIntAnnotations }}
  {{- with .Values.global.ecServiceK8Config.withIngress.ingressIntAnnotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- else -}}
  annotations:
    {}
  {{- end }}
spec:
  {{- include "ec-service.intIngress" . | nindent 2 }}
{{- end }}
{{- end }}