apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ec-service.fullname" . }}-pvc
  namespace: {{ .Values.global.efsPersistence.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.global.efsPersistence.storage }}
  storageClassName: {{ .Values.global.efsPersistence.storageClassName }}
  volumeMode: Filesystem
  volumeName: {{ include "ec-service.fullname" . }}-pv
status:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: {{ .Values.global.efsPersistence.storage }}
