apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ec-service.fullname" . }}
  labels:
    {{- include "ec-service.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: encrypted-efs
  resources:
    requests:
      storage: 6KiB