apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ec-service.fullname" . }}-pvc
  {{- if .Values.global.efsPersistence.namespace }}
  namespace: {{ .Values.global.efsPersistence.namespace }}
  {{- end }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      {{- if .Values.global.efsPersistence.storage }}
      storage: {{ .Values.global.efsPersistence.storage }}
      {{- else }}
      storage: 5M
      {{- end }}
  {{- if .Values.global.efsPersistence.storageClassName }}
  storageClassName: {{ .Values.global.efsPersistence.storageClassName }}
  {{- else }}
  storageClassName: efs.csi.aws.com
  {{- end }}
  volumeMode: Filesystem
  volumeName: {{ include "ec-service.fullname" . }}-pv
status:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: {{ .Values.global.efsPersistence.storage }}
