apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ec-service.fullname" . }}
  labels:
    {{- include "ec-service.labels" . | nindent 4 }}
  {{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}