{{- if .Values.global.agtK8Config.withIngress -}}
{{- $agtMode := include "agent.mode" . -}}
{{- if and (or (eq $agtMode "gateway") (eq $agtMode "gw:client") (eq $agtMode "gw:server")) (.Values.global.agtK8Config.withIngress.enabled) -}}
{{- $fullName := include "agent.fullname" . -}}
{{- $svcPort := .Values.global.agtK8Config.svcPortNum -}}
{{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1" }}
apiVersion: networking.k8s.io/v1
{{- else if $.Capabilities.APIVersions.Has "networking.k8s.io/v1beta1"}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-int
  labels:
    {{- include "agent.labels" . | nindent 4 }}
  annotations:
    {}
spec:
  {{- include "agent.intIngress" . | nindent 2 }}
{{- end }}
{{- end }}