{{- if .Values.global.agtK8Config.withIngress -}}
{{- if $.Values.global.agtK8Config.stsName -}}
{{- $agtMode := include "agent.mode" . -}}
{{- if (.Values.global.agtK8Config.withIngress.enabled) -}}
{{- $fullName := include "agentlber.fullname" . -}}
{{- $svcPort := 8080 -}}
{{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1" }}
apiVersion: networking.k8s.io/v1
{{- else if $.Capabilities.APIVersions.Has "networking.k8s.io/v1beta1"}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-int
  labels:
    {{- include "agentlber.labels" . | nindent 4 }}
  annotations:
    {}
spec:
  {{- include "agentlber.intIngress" . | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}