{{- if .Values.global.webportalK8Config.withIntIngress.enabled -}}
{{- $fullName := include "webportal.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-int
  labels:
    {{- include "webportal.labels" . | nindent 4 }}
  annotations:
    {}
spec:
  {{- include "webportal.ingress" . | nindent 2 }}
{{- end }}