{{- if .Values.global.webportalK8Config.efsPersistence.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "webportal.fullname" . }}
  labels:
    {{- include "webportal.labels" . | nindent 4 }}
    type: local
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  {{- toYaml .Values.global.webportalK8Config.efsPersistence.accessModes | nindent 4 }}
  persistentVolumeReclaimPolicy: {{ .Values.global.webportalK8Config.efsPersistence.reclaimPolicy | quote }}
  storageClassName: {{ .Values.global.webportalK8Config.efsPersistence.storageClassName | quote }}
  mountOptions:
  {{- toYaml .Values.global.webportalK8Config.efsPersistence.mountOptions | nindent 4 }}
  {{- if .Values.global.webportalK8Config.efsPersistence.fileSystemId }}
  csi:
    driver: {{ .Values.global.webportalK8Config.efsPersistence.provisioner  | quote }}
    volumeHandle: {{ printf "%s::%s" .Values.global.webportalK8Config.efsPersistence.fileSystemId .Values.global.webportalK8Config.efsPersistence.accessPointId }}
  {{- else }}
  hostPath:
    path: {{ .Values.global.webportalK8Config.efsPersistence.path | quote }}
  {{- end }}
 {{- end }}
# Storage class - EFS default, but can be override from values