apiVersion: v1
kind: Service
metadata:
  name: {{ include "webportal.fullname" . }}
  labels:
    {{- include "webportal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- include "webportal.svcPortSpec" . | nindent 4 }}
    {{- include "webportal.svcHealthPortSpec" . | nindent 4 }}
  selector:
    {{- include "webportal.selectorLabels" . | nindent 4 }}
