{{/*
 * Copyright (c) 2020 General Electric Company. All rights reserved.
 *
 * The copyright to the computer software herein is the property of
 * General Electric Company. The software may be used and/or copied only
 * with the written permission of General Electric Company or in accordance
 * with the terms and conditions stipulated in the agreement/contract
 * under which the software has been supplied.
 *
 * author: apolo.yasuda@ge.com
 */}}
 
{{- define "agent+helper.conf" -}}
{{- include "agent+helper.conf.merge" (append . "agent+helper.conf.tpl") -}}
{{- end -}}
{{- define "agent+helper.conf.tpl" -}}
env:
  {{ range .Files.Lines "conf.env" }}
  {{ $a := splitList "=" . }}
  - name: {{- printf "%s" (index $a 0 ) -}} 
    value: {{- printf "%s" (index $a 1 ) -}}
  {{ end }}
{{- end -}}
