{{- $fullName := include "agent.fullname" . -}}
{{- if .Values.global.agtK8Config.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $fullName }}-serviceaccount
  labels:
    {{- include "agent.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
