name: v1
on:
  push:
    branches: [ v1 ]
  pull_request:
    branches: [ v1 ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    environment: v1
    env:
      #helm chart version
      AGENT_CHART_REV: 0.1.8
      AGENT_HELPER_CHART_REV: 0.1.6
      AGENT_PLG_CHART_REV: 0.1.7
      AGENT_LBER_CHART_REV: 0.1.0
      AGENT_REV: v1.hokkaido.213
      
    steps:
      - uses: actions/checkout@v2
      
      - name: bootstrap minikube
        uses: manusa/actions-setup-minikube@v2.3.0
        with:
          minikube version: 'v1.16.0'
          kubernetes version: 'v1.19.2'
          #github token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: k8s sim test for the helm packages
        env:
          AGENT_REV: v1.hokkaido.213
          #EC_PPS: ${{secrets.EC_PPS_2_DECRYPT_213}}
        run: |
          chmod +x ./scripts/spec-sim.sh ./scripts/commonlib.sh
          source ./scripts/commonlib.sh
          source ./scripts/spec-sim.sh
          
      - name: helm packages deployment sim test
        env:
          AGENT_REV: v1.hokkaido.213
          #EC_PPS: ${{secrets.EC_PPS_2_DECRYPT_213}}
        run: |
          chmod +x ./scripts/k8s-deployment-sim.sh
          source ./scripts/commonlib.sh
          source ./scripts/k8s-deployment-sim.sh
          
      - name: publish distribution packages (ec-release/helmcharts)
        if: github.event.pull_request.merged == true
        uses: cpina/github-action-push-to-another-repository@master
        env:
          AGENT_REV: v1.hokkaido.213
          API_TOKEN_GITHUB: ${{ secrets.EC_CHART_DEPLOYMENT_TKN }}
        with:
          source-directory: 'k8s/pkg-new'
          destination-github-username: 'ec-release'
          destination-repository-name: 'helmcharts'
          target-branch: 'disty'
          commit-message: 'EC Bot Deployment'
          user-email: enterprise-connect@ge.com
      - name: publish distribution packages (ec-release/oci)
        if: github.event.pull_request.merged == true
        uses: cpina/github-action-push-to-another-repository@master
        env:
          AGENT_REV: v1.hokkaido.213
          API_TOKEN_GITHUB: ${{ secrets.EC_CHART_DEPLOYMENT_TKN }}
        with:
          source-directory: 'k8s/pkg'
          destination-github-username: 'ec-release'
          destination-repository-name: 'oci'
          target-branch: 'disty'
          commit-message: 'EC Bot Deployment'
          user-email: enterprise-connect@ge.com
