name: v1-ci
on:
  push:
    branches: [ v1 ]
  pull_request:
    branches: [ v1 ]
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    environment: v1
    env:
      #helm chart version
      AGENT_CHART_REV: 0.1.15
      AGENT_HELPER_CHART_REV: 0.1.13
      AGENT_PLG_CHART_REV: 0.1.14
      AGENT_LBER_CHART_REV: 0.1.7
      OAUTH_CHART_REV: 0.1.5
      AGENT_WEBPORTAL_CHART_REV: 0.1.5
      AGENT_REV: v1.hokkaido.213
      CA_PPRS: ${{ secrets.EC_PPS }}
      EC_OIDC_CID: ${{ secrets.EC_OIDC_CID }}
      EC_OIDC_CSC: ${{ secrets.EC_OIDC_CSC }}
      EC_PVTKEY: ${{ secrets.EC_PVTKEY }}

    steps:
      - uses: actions/checkout@v2

      - name: bootstrap minikube
        uses: manusa/actions-setup-minikube@v2.3.0
        with:
          minikube version: 'v1.16.0'
          kubernetes version: 'v1.19.2'
          #github token: ${{ secrets.GITHUB_TOKEN }}

      - name: k8s sim test for the helm packages
        env:
          AGENT_REV: v1.hokkaido.213
          #EC_PPS: ${{secrets.EC_PPS_2_DECRYPT_213}}
        run: |
          chmod +x ./scripts/spec-sim.sh ./scripts/commonlib.sh
          source ./scripts/commonlib.sh
          source ./scripts/spec-sim.sh

      - name: helm packages deployment sim test
        env:
          AGENT_REV: v1.hokkaido.213
          #EC_PPS: ${{secrets.EC_PPS_2_DECRYPT_213}}
        run: |
          chmod +x ./scripts/k8s-deployment-sim.sh
          source ./scripts/commonlib.sh
          source ./scripts/k8s-deployment-sim.sh

      - name: publish distribution packages 
        if: github.event_name == 'push'
        uses: ec-release/github-action-copy-files-folders-to-another-repos@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.EC_CHART_DEPLOYMENT_TKN }}
          GIT_USEREMAIL: ${{ secrets.EC_CHART_GIT_USEREMAIL }}
          GIT_USERNAME: ${{ secrets.EC_CHART_GIT_USERNAME }}
        with:
          SOURCE_DIR: 'k8s/pkg'
          DESTINATION_REPOS_BRANCHES: 'github.com/ec-release/oci.git:disty github.com/ec-release/helmcharts.git:disty'
          COMMIT_MESSAGE: 'Helm packages with tag v1.0.0-fukuoka-1'
          TAG_NAME: 'v1.0.0-fukuoka-1'
