name: v1
on:
  # Triggers the workflow on push or pull request events but only for the v1.1beta_helm_pkg_update_lber_ay branch
  push:
    branches: [ v1 ]
  pull_request:
    branches: [ v1 ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    environment: v1
    env:
      CHANGE_MINIKUBE_NONE_USER: true
      MINIKUBE_WANTUPDATENOTIFICATION: false
      MINIKUBE_WANTREPORTERRORPROMPT: false
      MINIKUBE_HOME: $HOME
      KUBECONFIG: $HOME/.kube/config
      #helm chart version
      AGENT_CHART_REV: 0.1.7
      AGENT_HELPER_CHART_REV: 0.1.5
      AGENT_PLG_CHART_REV: 0.1.6
      AGENT_LBER_CHART_REV: 0.1.0
      
    steps:
      - uses: actions/checkout@v2

      - name: bootstrap k8s sim test
        env:
          #EC_REV_V1: v1.hokkaido.213
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
          chmod +x ./scripts/spec-sim.sh
          
      - name: k8s sim test for the helm packages
        env:
          #AGENT_REV: v1.hokkaido.213
          #EC_PPS: ${{secrets.EC_PPS_2_DECRYPT_213}}
        run: |
          ./scripts/spec-sim.sh
