name: v1
on:
  # Triggers the workflow on push or pull request events but only for the v1.1beta_helm_pkg_update_lber_ay branch
  push:
    branches: [ v1 ]
  pull_request:
    branches: [ v1 ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    environment: v1
    env:
      #helm chart version
      AGENT_CHART_REV: 0.1.7
      AGENT_HELPER_CHART_REV: 0.1.5
      AGENT_PLG_CHART_REV: 0.1.6
      AGENT_LBER_CHART_REV: 0.1.0
      
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.3.0
        with:
          minikube version: 'v1.16.0'
          kubernetes version: 'v1.19.2'
          #github token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: k8s sim test for the helm packages
        env:
          AGENT_REV: v1.hokkaido.213
          #EC_PPS: ${{secrets.EC_PPS_2_DECRYPT_213}}
        run: |
          chmod +x ./scripts/spec-sim.sh
          source ./scripts/spec-sim.sh
          
      - name: helm packages deployment sim test
        env:
          AGENT_REV: v1.hokkaido.213
          #EC_PPS: ${{secrets.EC_PPS_2_DECRYPT_213}}
        run: |
          chmod +x ./scripts/k8s-deployment-sim.sh
          source ./scripts/k8s-deployment-sim.sh
          
      - name: push distributed packages
        if: github.event.pull_request.merged == true
        env:
          AGENT_REV: v1.hokkaido.213
          #EC_PPS: ${{secrets.EC_PPS_2_DECRYPT_213}}
        run: |
          echo packages push completed

